package main.Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    ADD_PROCEDURE,
    READ_PROCEDURES,
    DELETE_PROCEDURE,
    EDIT_DESCRIPTION,
    EDIT_PRICE,
    EDIT_DURATION,
    ADD_EMPLOYEE,
    READ_EMPLOYEES,
    GET_EMPLOYEE_SERVICES,
    CONNECT_PROCEDURE_EMPLOYEE,
    GET_PROCEDURES_FOR_TYPE,
    GET_EMPLOYEES_FOR_PROCEDURE,
    ADD_APPOINTMENT,
    ADD_PAYMENT,
    GET_APPOINTMENT_FOR_CLIENT,
    CANCEL_APPOINTMENT,
    EDIT_APPOINTMENT,
    SEARCH_PROCEDURES,
    GET_EMPLOYEES,
    GET_STATISTICS_PROCEDURES,
    GET_STATISTICS_EMPLOYEES,
    GET_STATISTICS_VISIT
}
