package main.Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    ADD_PROCEDURE,
    READ_PROCEDURES,
    DELETE_PROCEDURE,
    EDIT_DESCRIPTION,
    EDIT_PRICE,
    EDIT_DURATION,
    ADD_EMPLOYEE,
    READ_EMPLOYEES,
    GET_EMPLOYEE_SERVICES,
    CONNECT_PROCEDURE_EMPLOYEE
}
