package main.Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    ADD_PROCEDURE,
    READ_PROCEDURES,
    DELETE_PROCEDURE,
    EDIT_PRICE,
    EDIT_DESCRIPTION,
    EDIT_DURATION,
    ADD_EMPLOYEE,
    READ_EMPLOYEES,
    GET_EMPLOYEE_SERVICES,
    CONNECT_PROCEDURE_EMPLOYEE,
    GET_PROCEDURES_FOR_TYPE,
    GET_EMPLOYEES_FOR_PROCEDURE,
    ADD_APPOINTMENT,
    ADD_PAYMENT,
}
